"""The scanner's API responses, field by field, for tools/api_fields.py.

STRUCTS holds the structures several routes share; ROUTES each GET route's fields. A field is
(path, type, meaning); ("@path", "struct") includes a structure at that path ("@" alone: the
response itself). Paths: `a.b` a field of an object, `a[]` an array's elements, `a{key}` a map's
values. Types say "absent when ..." when the key is left out, and "or null" when the value can be
null. NOT_JSON describes the GET routes that do not answer JSON.
"""

STRUCTS: dict[str, list[tuple[str, str]] | list] = {}

STRUCTS["tuning"] = [
    ("preset", "string or null", "The DDC preset of the receive window (`8M`, `12M`, `16M`)."),
    ("sample_rate_hz", "number", "The AD9361's sample rate."),
    ("lo_hz", "number", "The window's centre (the nominal LO)."),
    ("lo_shift_hz", "number", "The crystal correction applied to the LO: the radio is commanded to `lo_hz + lo_shift_hz`."),
    ("crystal_ppm", "number", "The crystal correction in ppm (`lo_shift_hz` is `-ppm x lo_hz`)."),
    ("control_hz", "number", "The channel the control chain is tuned to."),
    ("gain", "object or null", "The receiver gain."),
    ("gain.mode", "string", "`manual`, `slow_attack`, `fast_attack` or `hybrid` (the AD9361's AGC modes)."),
    ("gain.db", "number or null", "The manual gain in dB; null under AGC."),
    ("lanes", "array of 2 numbers or null", "The channel each traffic lane is tuned to (lane 1, lane 2); null when the lane holds none."),
    ("rev", "number", "Counts tuning changes; a new value means something above moved."),
]

STRUCTS["site"] = [
    ("id", "string", "The site's id (used in every route that names a site)."),
    ("label", "string", "The site's name."),
    ("identity", "object", "What identifies the site on the air; each field is absent until known."),
    ("identity.rfss", "number, absent when unknown", "P25 RFSS."),
    ("identity.site", "number, absent when unknown", "P25 site, or the DMR site number."),
    ("identity.nac", "number, absent when unknown", "P25 NAC."),
    ("identity.lra", "number, absent when unknown", "P25 location registration area."),
    ("identity.colour_code", "number, absent when unknown", "DMR colour code."),
    ("control", "object", "The control channel."),
    ("control.freq_hz", "number", "The control channel's downlink."),
    ("control.alternates_hz", "array of numbers, absent when none", "Other control channels the site has used."),
    ("control.lcn", "number, absent when unknown", "DMR: the control channel's logical channel number."),
    ("control.timeslot", "number, absent when unknown", "DMR: the timeslot carrying the control messages."),
    ("modulation", "string", "`auto` (the scanner chooses LSM or C4FM by what decodes better), `lsm` or `c4fm`."),
    ("channels_hz", "array of numbers, absent when none", "Known traffic channels (the window planner's starting set)."),
    ("channel_plan", "object, absent when none", "DMR: the logical channel plan."),
    ("channel_plan.lcn_hz", "map", "LCN to downlink frequency (a DMR grant names an LCN)."),
    ("channel_plan.lcn_hz{key}", "number", "The LCN's downlink, Hz."),
    ("window", "object", "How the receive window is chosen."),
    ("window.auto", "bool", "The planner chooses the window (and may recentre it)."),
    ("window.min_preset", "string or null", "The narrowest preset the planner may use; null for no limit."),
    ("window.cc_position", "string", "Where the control channel sits in the window: `center`, `top` (traffic below) or `bottom`."),
    ("notes", "array of strings, absent when none", "Free notes."),
    ("notes[]", "string", "One note."),
    ("source", "string, absent when unknown", "Where the site came from (the scan that found it)."),
]

STRUCTS["system"] = [
    ("id", "string", "The system's id."),
    ("label", "string", "The system's name."),
    ("protocol", "string", "`p25` or `dmr_tier3`."),
    ("identity", "object", "What identifies the system; each field is absent until known."),
    ("identity.wacn", "number, absent when unknown", "P25 WACN."),
    ("identity.system", "number, absent when unknown", "P25 system id."),
    ("identity.model", "string, absent when unknown", "DMR Tier III network model: `tiny`, `small`, `large` or `huge`."),
    ("identity.network", "number, absent when unknown", "DMR Tier III network."),
    ("details", "object", "What describes the system beside its identity, as RadioReference lists it; the radio does not act on it."),
    ("details.location", "string, absent when not set", "Where it is, e.g. `Green Cove Springs, FL`."),
    ("details.county", "string, absent when not set", "Its county."),
    ("details.system_type", "string, absent when not set", "Its type, e.g. `Project 25 Phase I`."),
    ("details.voice", "string, absent when not set", "Its voice, e.g. `APCO-25 Common Air Interface Exclusive`."),
    ("aliases", "array", "What the radio knows of the system's talkgroups and radios (SDRTrunk's alias list)."),
    ("@aliases[]", "alias"),
    ("listening", "object", "Talkgroups with no priority, and pre-emption."),
    ("@listening", "listening"),
    ("sites", "array", "The system's sites."),
    ("@sites[]", "site"),
]

STRUCTS["alias"] = [
    ("name", "string", "Shown wherever its talkgroup or radio appears."),
    ("group", "string, absent when none", "A free label to sort and filter by (SDRTrunk's alias group)."),
    ("color", "string, absent when none", "`#rrggbb`."),
    ("ids", "array", "The talkgroups and radios it names."),
    ("ids[]", "object", "One ID; `type` says which fields follow."),
    ("ids[].type", "string", "`talkgroup`, `talkgroup_range`, `radio` or `radio_range`."),
    ("ids[].value", "number, absent for a range", "The talkgroup or radio."),
    ("ids[].min", "number, absent unless a range", "The range's first."),
    ("ids[].max", "number, absent unless a range", "The range's last."),
    ("priority", "number or null", "Monitor priority, 1 (highest) to 100 (lowest); a higher one takes a traffic channel from a lower one. Null: unmonitored (see `listening`)."),
    ("do_not_monitor", "bool", "Never followed (SDRTrunk's priority -1)."),
    ("record", "bool", "Its calls are recorded (when recording is not set to every call)."),
    ("speaker", "string", "Where it plays: `both`, `left` or `right`."),
    ("icon", "string, absent when none", "SDRTrunk's icon name, kept for the round trip."),
]

STRUCTS["listening"] = [
    ("follow_unmonitored", "bool", "Talkgroups with no priority (no alias, or an alias without one) are followed at the lowest priority; false: only those with a priority (SDRTrunk's \"ignore unmonitored calls\")."),
    ("unmonitored_speaker", "string", "Where those play: `both`, `left` or `right`."),
    ("preempt", "bool", "A higher priority takes a traffic channel from a lower one."),
]

STRUCTS["radio_config"] = [
    ("version", "number", "The file format's version."),
    ("gain", "object", "The receiver gain setting."),
    ("gain.mode", "string", "`manual`, `slow_attack`, `fast_attack` or `hybrid`."),
    ("gain.manual_db", "number or null", "The gain in manual mode, dB."),
    ("presets_allowed", "array of strings", "DDC presets the window planner may choose, narrowest first."),
    ("presets_allowed[]", "string", "One preset."),
    ("traffic_chains", "number or null", "Traffic lanes to run; null: every lane the gateware has (applies at the next start)."),
    ("calls", "object", "Call timing."),
    ("calls.hang_ms", "number", "A call with no voice, update or terminator for this long closes."),
    ("calls.end_grace_ms", "number", "After an end-of-transmission marker, the call closes this long later unless voice resumes."),
    ("recording", "object", "Call recordings."),
    ("recording.enabled", "bool", "Followed calls are recorded."),
    ("recording.every_call", "bool", "Every followed call; false: only those whose alias says record."),
    ("recording.storage", "string", "Where new recordings go: `sd` or `ram`."),
    ("recording.ram_max_count", "number", "Recordings kept in RAM."),
    ("recording.sd_max_count", "number", "Recordings kept on the card."),
    ("recording.sd_max_mb", "number", "Space the card's recordings may use, MB."),
    ("history", "object", "The call history."),
    ("history.retention_days", "number", "Calls older than this are removed."),
    ("history.sd_max_mb", "number", "Space the history may use on the card, MB."),
    ("clock", "object", "The board clock."),
    ("clock.source", "string", "`site` (the control channel's time), `ntp` or `manual`."),
    ("crystal", "object", "Crystal tracking."),
    ("crystal.tracking", "bool", "The correction follows the live site's carrier."),
    ("crystal.anchor_hz", "number", "How far tracking may move from this run's calibration, Hz at the LO (0: no limit)."),
]

STRUCTS["window_plan"] = [
    ("preset", "string", "The DDC preset."),
    ("sample_rate_hz", "number", "Its sample rate."),
    ("lo_hz", "number", "The window's centre."),
    ("usable_half_hz", "number", "How far from the centre a channel can be received."),
    ("covered_weight", "number", "The weight of the site's channels inside the window (channels weighted by their grants)."),
    ("total_weight", "number", "The weight of all the site's channels."),
]

STRUCTS["heard_identity"] = [
    ("protocol", "string", "`p25` or `dmr`; the other fields depend on it."),
    ("nac", "number or null", "P25 NAC (null until heard)."),
    ("wacn", "number or null", "P25 WACN."),
    ("system", "number or null", "P25 system id."),
    ("rfss", "number or null", "P25 RFSS."),
    ("site", "number or null", "P25 site, or the DMR site number."),
    ("lra", "number or null", "P25 location registration area."),
    ("colour_code", "number", "DMR colour code."),
    ("model", "string", "DMR network model: `TINY`, `SMALL`, `LARGE` or `HUGE`."),
    ("network", "number", "DMR network."),
]

STRUCTS["control"] = [
    ("running", "bool", "The control channel decoder runs."),
    ("site", "string, absent when stopped", "The site it decodes."),
    ("identity", "object, absent until heard", "The site's identity as broadcast."),
    ("@identity", "heard_identity"),
    ("modulation", "string, absent at DMR sites", "P25: the demodulator whose messages are used, `lsm` (gateware) or `c4fm` (software)."),
    ("tsbks_20s", "object, absent at DMR sites", "P25: TSBKs each demodulator passed in the last 20 s (what the automatic choice compares)."),
    ("tsbks_20s.lsm", "number", "By the gateware LSM demodulator."),
    ("tsbks_20s.c4fm", "number", "By the software C4FM demodulator."),
    ("msgs_per_s", "number or null", "Messages that passed their checks, per second (over the last few seconds)."),
    ("ok_pct", "number or null", "Share of messages that passed their checks (P25: TSBK CRC), %."),
    ("last_message_age_ms", "number or null", "Since the last message that passed, ms."),
    ("cpu_pct", "number", "Share of one core the decode thread uses, %."),
    ("carrier_offset_hz", "number, absent at P25 sites", "DMR: the carrier's offset from the channel as the equaliser measures it."),
    ("channel_plan_entries", "number", "Channel plan entries known: P25 band (IDEN) entries, DMR LCNs."),
    ("neighbours", "number", "P25: neighbour sites announced."),
    ("grants", "number", "Voice grants decoded since the site went live."),
    ("grants_dropped", "number", "Grants the trunking task could not take (its queue was full)."),
    ("input", "object", "What the stream readers delivered."),
    ("input.iq_chunks", "number", "Control IQ chunks delivered."),
    ("input.iq_dropped", "number", "IQ chunks dropped because the decoder was behind."),
    ("input.dibit_bytes", "number", "Bytes of gateware dibits delivered (four dibits a byte)."),
    ("input.dibit_resyncs", "number", "Times the dibit stream skipped and was resynchronised."),
    ("input.dibit_lost", "number", "Dibit deliveries lost (decoder behind, or a copy failed)."),
]

STRUCTS["framer"] = [
    ("dibits", "number", "Dibits framed."),
    ("dibit_hist", "array of 4 numbers", "Dibits by value (0 to 3)."),
    ("sync_hits", "number", "Frame syncs found."),
    ("sync_distance_hist", "array of 25 numbers", "Correlator distance per dibit while hunting for sync (the last bucket: 24 or more)."),
    ("nid_bch_failures", "number", "NIDs the BCH code could not correct."),
    ("nid_entropy_rejected", "number", "NIDs rejected because one dibit value dominated (noise, not a frame)."),
    ("nid_invalid_duid", "number", "NIDs with an unknown data unit id."),
    ("nid_nac_mismatch", "number", "NIDs with another site's NAC, dropped."),
    ("nid_ok", "number", "NIDs accepted."),
    ("nac_relocks", "number", "Times the framer moved to a NAC that had become the dominant one."),
    ("raw_duid_hist", "array of 16 numbers", "The on-air DUID nibble of accepted NIDs."),
    ("tsdus", "number", "Trunking signalling data units (control channel frames)."),
    ("tsbk_attempts_by_pos", "array of 3 numbers", "TSBKs tried, by their position in the TSDU (first, second, third)."),
    ("tsbk_ok_by_pos", "array of 3 numbers", "TSBKs that passed, by position."),
    ("tsbk_trellis_failures", "number", "TSBKs the trellis decoder could not decode."),
    ("tsbk_crc_failures", "number", "TSBKs that failed their CRC."),
    ("tsbk_crc_plain", "number", "TSBKs whose CRC matched the standard convention."),
    ("tsbk_crc_xored", "number", "TSBKs whose CRC matched with the final XOR left out (some sites send this)."),
    ("tsbk_unknown_opcode", "number", "TSBKs that passed but have an opcode the decoder does not parse."),
    ("tsbk_opcodes_ok", "array of 64 numbers", "TSBKs passed, by opcode (0 to 63)."),
    ("tsbk_opcodes_failed", "array of 64 numbers", "TSBKs failed, by opcode."),
    ("tsbk_mfid_ok", "array of 4 numbers", "TSBKs passed by manufacturer: standard, Motorola (0x90), Harris (0xA4), other."),
    ("hdus", "number", "Header data units (a call's start)."),
    ("ldu1s", "number", "Logical data units 1 (voice, link control)."),
    ("ldu2s", "number", "Logical data units 2 (voice, encryption sync)."),
    ("tdus", "number", "Terminators."),
    ("tdu_lcs", "number", "Terminators with link control."),
    ("pdus", "number", "Packet data units."),
    ("pdu_header_failures", "number", "PDU headers that failed their checks."),
    ("pdu_blocks", "number", "PDU data blocks read."),
]

STRUCTS["dmr_demod"] = [
    ("symbols", "number", "Symbols demodulated."),
    ("coarse_syncs", "number", "Syncs found from scratch (the coarse timing search)."),
    ("fine_syncs", "number", "Syncs confirmed where the next burst was expected."),
    ("fine_sync_losses", "number", "Expected syncs that were not there (fine sync dropped)."),
]

STRUCTS["dmr_messages"] = [
    ("bursts", "array of 3 numbers", "Bursts by timeslot: unknown, 1, 2."),
    ("voice_bursts", "number", "Voice bursts."),
    ("cach_ok", "number", "CACH (the slot-type channel) decoded."),
    ("cach_bad", "number", "CACH that failed."),
    ("sync_loss_bits", "number", "Bits processed while sync was lost."),
    ("msgs_valid", "number", "Messages that passed their checks."),
    ("msgs_invalid", "number", "Messages that failed."),
    ("classes", "map", "Messages by SDRTrunk class name."),
    ("classes{key}", "array of 2 numbers", "Passed and failed."),
]

STRUCTS["call"] = [
    ("call", "number", "The call's id (also its recording's id)."),
    ("site", "string", "The site it was heard on."),
    ("tg", "number", "The talkgroup; for a private call, the called radio."),
    ("tg_name", "string or null", "The talkgroup's name in the site's system (the called radio's for a private call)."),
    ("source", "number or null", "The calling radio: the grant's, else the voice's."),
    ("source_name", "string or null", "The calling radio's name."),
    ("speaker", "number or null", "The radio the voice link control named last (who is talking now)."),
    ("sources", "array of numbers", "Every radio heard in the call, in order."),
    ("freq_hz", "number or null", "The traffic channel's downlink."),
    ("channel", "string or null", "The channel as the control channel names it (P25 `iden-number`, DMR LCN)."),
    ("slot", "number or null", "DMR: the timeslot."),
    ("encrypted", "bool", "Encrypted (not followed)."),
    ("emergency", "bool", "Granted as an emergency call."),
    ("private", "bool", "A unit-to-unit call."),
    ("not_followed", "string or null", "Why no lane followed it: `encrypted`, `busy`, `monitor_list`, `ignored`, `speaker_off`, `out_of_band`, `phase2`, `unknown_lcn` or `held`; null: followed."),
    ("lane", "number or null", "The lane that followed it (1 or 2)."),
    ("started_unix_ms", "number", "The grant."),
    ("first_voice_unix_ms", "number or null", "The first voice frame."),
    ("ended_unix_ms", "number or null", "The close; null while open."),
    ("open_ms", "number or null", "From the grant to the close; null while open."),
    ("grant_ms", "number or null", "From the grant to its last update on the control channel."),
    ("close", "string or null", "Why it closed: `call_end` (end of transmission), `timeout`, `tg_change` (another call took the channel or lane) or `site_switch`."),
    ("end_lc", "string or null", "The end-of-transmission marker seen, if any."),
    ("voice_frames", "number", "Voice frames decoded (20 ms each)."),
    ("codec", "string or null", "`imbe` (P25) or `ambe2` (DMR), once there was voice."),
    ("frame_errors", "number or null", "Voice frames the vocoder found errors in; known once the call is stored."),
]

STRUCTS["window"] = [
    ("window", "object", "The period the answer covers."),
    ("window.site", "string", "The site, or the system when `system` is true."),
    ("window.system", "bool", "The answer covers every site of a system."),
    ("window.from_ms", "number", "Start (unix ms)."),
    ("window.to_ms", "number", "End (unix ms)."),
    ("window.first_hour_ms", "number", "The first whole hour the hourly totals use."),
]

STRUCTS["crystal_cal"] = [
    ("at_unix_ms", "number", "When it was measured."),
    ("lo_hz", "number", "The LO at the time."),
    ("control_hz", "number", "The control channel it measured."),
    ("source", "string", "What it measured with: `p25_loop`, `dmr_equaliser` or `spectrum`."),
    ("spectrum_offset_hz", "number", "The carrier's offset in the wideband spectrum."),
    ("spectrum_db", "number", "The carrier's level in the spectrum, dB."),
    ("residual_hz", "number or null", "The decoder's mean carrier offset after the spectrum step."),
    ("residual_samples", "number", "Readings averaged for it."),
    ("ppm_before", "number", "The correction before."),
    ("ppm", "number", "The correction it set."),
    ("duration_ms", "number", "How long it took."),
]

STRUCTS["lsm_control"] = [
    ("enable", "bool", "The demodulator runs."),
    ("dibit_dma", "bool", "Its dibits go to memory."),
    ("dc_block", "bool", "The DC blocker is on."),
    ("agc", "bool", "Its AGC is on."),
]

STRUCTS["named_stat"] = [
    ("calls", "number", "Calls."),
    ("encrypted", "number", "Encrypted calls."),
    ("voice_s", "number", "Decoded voice, seconds."),
    ("grant_s", "number", "Grant time of calls with no decoded voice, seconds."),
    ("last_ms", "number", "The newest call (unix ms)."),
    ("alias", "string or null", "The name in the system."),
]

STRUCTS["recording"] = [
    ("id", "number", "The call's id."),
    ("site", "string", "The site (empty for recordings older than sites)."),
    ("tg", "number", "The talkgroup."),
    ("source", "number or null", "The calling radio."),
    ("started_unix_ms", "number", "The call's start."),
    ("duration_ms", "number", "The recording's length."),
    ("bytes", "number", "The file's size."),
    ("file", "string", "The file's name."),
    ("store", "string", "`sd` or `ram`."),
    ("sd_pending", "bool", "Still waiting to be written to the card (served from RAM meanwhile)."),
    ("sources", "array of numbers", "Every radio heard."),
    ("lane", "number, absent for earlier runs' recordings", "The lane that recorded it."),
    ("freq_hz", "number, absent for earlier runs' recordings", "The traffic channel."),
    ("channel", "string, absent for earlier runs' recordings", "The channel as announced."),
    ("voice", "object, absent for earlier runs' recordings", "The vocoder's counts."),
    ("voice.frames", "number", "Voice frames."),
    ("voice.errors", "number", "Frames with errors."),
    ("voice.silent", "number", "Frames decoded as silence."),
]

STRUCTS["carrier"] = [
    ("freq_hz", "number", "The carrier."),
    ("level_db", "number", "Its level, dB."),
    ("persistence", "number", "Share of the sweep's frames it was present in."),
]

S = STRUCTS

ROUTES: dict[str, list] = {
    "/api/v1/routes": [
        ("[]", "object", "One route."),
        ("[].method", "string", "`get`, `put`, `post` or `delete`."),
        ("[].path", "string", "The path; `{name}` is a parameter."),
        ("[].summary", "string", "What it does."),
    ],
    "/api/v1/status": [
        ("build", "string", "The scanner's build tag."),
        ("uptime_s", "number", "Since the scanner started, s."),
        ("now_unix_ms", "number", "The board's clock."),
        ("live", "object", "The live site's state; `state` says which fields follow."),
        ("live.state", "string", "`no_site`, `switching` (with `to`), `scanning` (with `back_to`) or `live` (with the fields below)."),
        ("live.to", "string, absent unless switching", "The site being made live."),
        ("live.back_to", "string or null, absent unless scanning", "The site the scan returns to."),
        ("live.site", "object, absent unless live", "The live site's configuration."),
        ("@live.site", "site"),
        ("live.system", "object, absent unless live", "Its system."),
        ("live.system.id", "string", "The system's id."),
        ("live.system.label", "string", "The system's name."),
        ("live.system.protocol", "string", "`p25` or `dmr_tier3`."),
        ("live.window", "object, absent unless live", "The receive window the planner chose."),
        ("@live.window", "window_plan"),
        ("live.tuning", "object, absent unless live", "The tuning (the same as `tuning`)."),
        ("@live.tuning", "tuning"),
        ("control", "object", "The control channel decoder."),
        ("@control", "control"),
        ("lease", "string", "Who has the radio: `normal`, `switching` (a site going live) or `scan`."),
        ("tuning", "object", "The tuning."),
        ("@tuning", "tuning"),
        ("clock", "object", "The board clock."),
        ("clock.source", "string", "`site`, `ntp` or `manual`."),
        ("clock.valid", "bool", "The board clock has been set (otherwise it counts from 1970)."),
        ("clock.site_precision", "string or null", "How precise the site's time is: `minute`, `second` or `precise`."),
        ("clock.site_offset_ms", "number or null", "The site's time minus the board's."),
        ("clock.last_set", "string or null", "When and from what the clock was last set."),
        ("hold", "number or null", "The talkgroup the live site is held on."),
    ],
    "/api/v1/calls": [
        ("open", "array", "Calls on the air now: followed first (by lane), then those not followed."),
        ("@open[]", "call"),
        ("recent", "array", "The live site's newest 100 closed calls, newest first."),
        ("@recent[]", "call"),
    ],
    "/api/v1/calls/{id}": [("@", "call")],
    "/api/v1/hold": [
        ("site", "string or null", "The live site; null when none."),
        ("tg", "number or null", "The held talkgroup; null when not held."),
        ("name", "string or null", "The held talkgroup's name."),
    ],
    "/api/v1/data": [
        ("site", "string or null", "The site the answer covers; null for every site."),
        ("data_channel_hz", "number or null", "The data channel the site announces."),
        ("pdus", "number", "Packet data units read."),
        ("duplicates", "number", "The same PDU read again by a second decoder (not counted twice)."),
        ("totals", "map", "PDUs by kind (`packet/lrrp`, `packet/ars`, `ambtc`, `response/...`)."),
        ("totals{key}", "number", "PDUs of that kind."),
        ("radios", "array", "Radios with packet data, newest first (at most 200)."),
        ("radios[]", "object", "One radio at one site."),
        ("radios[].site", "string", "The site."),
        ("radios[].llid", "number", "The radio (logical link id)."),
        ("radios[].alias", "string or null", "Its name."),
        ("radios[].packets", "number", "Its PDUs."),
        ("radios[].inbound", "number", "From the radio."),
        ("radios[].outbound", "number", "To the radio."),
        ("radios[].bytes", "number", "User data bytes."),
        ("radios[].first_ms", "number", "First heard (unix ms)."),
        ("radios[].last_ms", "number", "Last heard (unix ms)."),
        ("radios[].kinds", "map", "Its PDUs by kind."),
        ("radios[].kinds{key}", "number", "PDUs of that kind."),
        ("radios[].ip", "string or null", "Its IP address, once seen."),
        ("recent", "array", "PDUs newest first (`limit`)."),
        ("recent[]", "object", "One PDU."),
        ("recent[].at_ms", "number", "When it was read (unix ms)."),
        ("recent[].site", "string", "The site."),
        ("recent[].chain", "string", "The decoder that read it: `control`, `lane 1`, `lane 2`."),
        ("recent[].nac", "number", "The NAC it carried."),
        ("recent[].outbound", "bool", "From the site to the radio."),
        ("recent[].format", "string", "PDU format: `packet`, `ambtc`, `response`, `unconfirmed`..."),
        ("recent[].sap", "string", "Service access point by name (for a response: the response class)."),
        ("recent[].sap_id", "number", "The SAP number."),
        ("recent[].llid", "number", "The radio."),
        ("recent[].alias", "string or null", "Its name."),
        ("recent[].mfid", "number", "Manufacturer id."),
        ("recent[].confirmed", "bool", "Confirmed delivery."),
        ("recent[].blocks", "number", "Data blocks read."),
        ("recent[].blocks_expected", "number", "Data blocks the header announced."),
        ("recent[].bad_blocks", "number", "Blocks that failed their CRC-9."),
        ("recent[].block_errors", "array of numbers", "Bit errors corrected per block."),
        ("recent[].crc_ok", "bool or null", "The packet's CRC-32 passed (null: not a whole packet)."),
        ("recent[].sndcp", "array of 4 numbers or null", "SNDCP header: type, NSAPI, IP compression, UDP compression."),
        ("recent[].ip", "object or null", "The IP header, when it carries IP."),
        ("recent[].ip.src", "string", "Source address."),
        ("recent[].ip.dst", "string", "Destination address."),
        ("recent[].ip.protocol", "number", "IP protocol (17: UDP)."),
        ("recent[].ip.total_len", "number", "IP length."),
        ("recent[].ip.src_port", "number or null", "UDP source port."),
        ("recent[].ip.dst_port", "number or null", "UDP destination port."),
        ("recent[].service", "string or null", "The service its UDP port names (LRRP, ARS...)."),
        ("recent[].bytes", "number", "User data bytes."),
        ("recent[].opcode", "number or null", "AMBTC: the opcode."),
        ("recent[].response", "number or null", "Response: the response octet."),
        ("recent[].hex", "string", "The user data, hex (at most 64 bytes)."),
    ],
    "/api/v1/activity/sites": [
        ("active", "string or null", "The live site, else the last one live."),
        ("sites", "array", "Sites with history."),
        ("sites[]", "object", "One site."),
        ("sites[].site", "string", "The site."),
        ("sites[].label", "string", "Its name."),
        ("sites[].system", "string or null", "Its system."),
        ("sites[].calls", "number", "Calls kept."),
        ("sites[].first_ms", "number", "The oldest call (unix ms)."),
        ("sites[].last_ms", "number", "The newest call (unix ms)."),
        ("database", "string", "The history file."),
        ("on_sd", "bool", "On the card (else in RAM, lost on restart)."),
        ("size_bytes", "number", "The file's size."),
        ("used_bytes", "number", "Space its data uses."),
        ("max_bytes", "number", "The limit; the oldest calls go past it."),
        ("retention_days", "number", "Calls older than this go."),
    ],
    "/api/v1/activity/summary": [
        ("@", "window"),
        ("summary", "object", "Totals over the window."),
        ("summary.calls", "number", "Calls."),
        ("summary.followed", "number", "Calls a lane followed."),
        ("summary.encrypted", "number", "Encrypted calls."),
        ("summary.voice_s", "number", "Decoded voice, s."),
        ("summary.clear_grant_s", "number", "Grant time of clear calls, s."),
        ("summary.encrypted_grant_s", "number", "Grant time of encrypted calls, s."),
        ("summary.voice_per_grant", "number or null", "Voice time per grant time of the calls with voice; null without any."),
        ("summary.talkgroups", "number", "Talkgroups heard."),
        ("summary.radios", "number", "Radios heard."),
        ("summary.first_ms", "number or null", "The first call (unix ms)."),
        ("summary.last_ms", "number or null", "The last call (unix ms)."),
    ],
    "/api/v1/activity/talkgroups": [
        ("@", "window"),
        ("items", "array", "Talkgroups by time, most first (`limit`)."),
        ("items[]", "object", "One talkgroup."),
        ("items[].tg", "number", "The talkgroup."),
        ("@items[]", "named_stat"),
        ("items[].radios", "number", "Radios heard on it."),
    ],
    "/api/v1/activity/radios": [
        ("@", "window"),
        ("items", "array", "Radios by time, most first (`limit`)."),
        ("items[]", "object", "One radio."),
        ("items[].unit", "number", "The radio."),
        ("@items[]", "named_stat"),
        ("items[].talkgroups", "number", "Talkgroups it used."),
    ],
    "/api/v1/activity/radio/{unit}": [
        ("@", "window"),
        ("radio", "object", "The radio."),
        ("radio.unit", "number", "The radio."),
        ("radio.alias", "string or null", "Its name."),
        ("radio.talkgroups", "array", "Talkgroups it used."),
        ("radio.talkgroups[]", "object", "One talkgroup."),
        ("radio.talkgroups[].tg", "number", "The talkgroup."),
        ("@radio.talkgroups[]", "named_stat"),
        ("radio.events", "array", "Affiliations and registrations."),
        ("radio.events[]", "object", "One kind of event on one talkgroup."),
        ("radio.events[].tg", "number", "The talkgroup (0 for a registration)."),
        ("radio.events[].kind", "string", "`group_affiliation`, `registration` or `deregistration`."),
        ("radio.events[].first_ms", "number", "First seen (unix ms)."),
        ("radio.events[].last_ms", "number", "Last seen (unix ms)."),
        ("radio.events[].count", "number", "Times seen."),
        ("radio.events[].alias", "string or null", "The talkgroup's name."),
    ],
    "/api/v1/activity/talkgroup/{tg}": [
        ("@", "window"),
        ("talkgroup", "object", "The talkgroup."),
        ("talkgroup.tg", "number", "The talkgroup."),
        ("talkgroup.alias", "string or null", "Its name."),
        ("talkgroup.radios", "array", "Radios heard on it."),
        ("talkgroup.radios[]", "object", "One radio."),
        ("talkgroup.radios[].unit", "number", "The radio."),
        ("@talkgroup.radios[]", "named_stat"),
        ("talkgroup.calls", "number", "Calls."),
        ("talkgroup.encrypted", "number", "Encrypted calls."),
        ("talkgroup.first_encrypted_ms", "number or null", "The first encrypted call (unix ms)."),
        ("talkgroup.last_encrypted_ms", "number or null", "The last encrypted call."),
        ("talkgroup.last_clear_ms", "number or null", "The last clear call."),
        ("talkgroup.affiliated_radios", "number", "Radios that affiliated to it."),
    ],
    "/api/v1/activity/series": [
        ("@", "window"),
        ("bucket_ms", "number", "The bucket's length (an hour or a day)."),
        ("tz", "number", "The time zone the days are cut in, minutes east of UTC."),
        ("buckets", "array", "One per hour or day, oldest first (empty ones included)."),
        ("buckets[]", "object", "One bucket."),
        ("buckets[].t", "number", "Its start (unix ms)."),
        ("buckets[].calls", "number", "Calls."),
        ("buckets[].encrypted", "number", "Encrypted calls."),
        ("buckets[].voice_s", "number", "Decoded voice, s."),
        ("buckets[].clear_grant_s", "number", "Grant time of clear calls, s."),
        ("buckets[].encrypted_grant_s", "number", "Grant time of encrypted calls, s."),
    ],
    "/api/v1/activity/calls": [
        ("@", "window"),
        ("items", "array", "Calls, newest first (`limit`)."),
        ("@items[]", "call"),
    ],
    "/api/v1/spectrum": [
        ("lo_hz", "number", "The window's centre."),
        ("sample_rate_hz", "number", "Its width."),
        ("control_hz", "number", "The control channel."),
        ("lanes_hz", "array of 2 numbers or null", "Each lane's channel."),
        ("db", "array of numbers", "Power per bin, dB, from -rate/2 to +rate/2 (each the strongest of its group)."),
        ("fresh", "bool", "A new frame (false: the last one again, during a scan or when none came in 300 ms)."),
    ],
    "/api/v1/events": [
        ("events", "array", "Events after `after`, oldest first."),
        ("events[]", "object", "One event."),
        ("events[].seq", "number", "Its sequence number (ask for those after it next)."),
        ("events[].unix_ms", "number", "When."),
        ("events[].source", "string", "`p25`, `dmr` (a message) or `system` (the scanner)."),
        ("events[].class", "string", "The message class, or the system event's kind (`call`, `follow`, `hold`, `crystal`...)."),
        ("events[].text", "string", "The event."),
        ("events[].routine", "bool", "Housekeeping (left out unless `routine=true`)."),
        ("events[].valid", "bool", "The message passed its checks."),
        ("events[].slot", "number, absent when none", "DMR: the timeslot."),
        ("events[].tg", "number, absent when none", "The talkgroup it names."),
        ("events[].unit", "number, absent when none", "The radio it names."),
    ],
    "/api/v1/system": [
        ("at_unix_ms", "number", "When it was sampled (every 5 s)."),
        ("board_uptime_s", "number or null", "Since the board booted."),
        ("load", "array of 3 numbers or null", "Load average over 1, 5 and 15 minutes."),
        ("mem_total_kb", "number or null", "Memory."),
        ("mem_available_kb", "number or null", "Memory free for use."),
        ("core_cpu_pct", "array of numbers", "Each core's use, %."),
        ("rss_kb", "number or null", "The scanner's memory."),
        ("threads", "number or null", "The scanner's threads."),
        ("cpu_pct", "number or null", "The scanner's share of one core, %."),
        ("thread_cpu", "array", "The scanner's threads by use, busiest first."),
        ("thread_cpu[]", "object", "One thread."),
        ("thread_cpu[].name", "string", "Its name."),
        ("thread_cpu[].cpu_pct", "number", "Its share of one core, %."),
        ("ad9361_temp_c", "number or null", "The AD9361's temperature, °C."),
        ("zynq_temp_c", "number or null", "The Zynq's temperature, °C."),
    ],
    "/api/v1/receivers": [
        ("control", "object", "The control channel decoder (the fields of `/status` `control`, and those below)."),
        ("@control", "control"),
        ("control.loop", "object or null", "The control chain's gateware carrier loop and AGC (P25)."),
        ("control.loop.pll_q213", "number", "The loop's phase correction per symbol, Q2.13 (one reading)."),
        ("control.loop.pll_hz", "number", "The same in Hz."),
        ("control.loop.agc_gain", "number", "The LSM AGC's gain, Q9.7."),
        ("control.loop.agc_mag", "number", "The LSM AGC's magnitude, Q1.15."),
        ("control.counters", "object or null", "The decoders' counters; `protocol` says which."),
        ("control.counters.protocol", "string", "`p25` (with `lsm` and `c4fm`) or `dmr` (with `messages` and `demod`)."),
        ("control.counters.lsm", "object", "P25: the gateware LSM demodulator's framer."),
        ("@control.counters.lsm", "framer"),
        ("control.counters.c4fm", "object", "P25: the software C4FM demodulator's framer."),
        ("@control.counters.c4fm", "framer"),
        ("control.counters.messages", "object", "DMR: the message decoder."),
        ("@control.counters.messages", "dmr_messages"),
        ("control.counters.demod", "object", "DMR: the demodulator."),
        ("@control.counters.demod", "dmr_demod"),
        ("lanes", "array", "Each traffic lane of the live site (empty when none is live)."),
        ("lanes[]", "object", "One lane."),
        ("lanes[].lane", "number", "1 or 2."),
        ("lanes[].tuned_hz", "number or null", "The channel it is tuned to."),
        ("lanes[].call", "number or null", "The call it carries."),
        ("lanes[].following_tg", "number or null", "The talkgroup the follower keeps it for."),
        ("lanes[].on_data_channel", "bool", "Waiting on the site's data channel between calls."),
        ("lanes[].voice_frames", "number", "Voice frames decoded on it since the site went live."),
        ("lanes[].last_voice_ms_ago", "number or null", "Since its last voice frame."),
        ("lanes[].counters", "object", "Its traffic decoder's counters; `protocol` says which."),
        ("lanes[].counters.protocol", "string", "`p25` (the framer's fields) or `dmr` (`bursts` and `demod`)."),
        ("@lanes[].counters", "framer"),
        ("lanes[].counters.bursts", "number", "DMR: bursts read."),
        ("lanes[].counters.demod", "object", "DMR: the demodulator."),
        ("@lanes[].counters.demod", "dmr_demod"),
        ("lanes[].loop", "object or null", "Its gateware carrier loop."),
        ("lanes[].loop.pll_q213", "number", "Phase correction per symbol, Q2.13 (one reading)."),
        ("lanes[].loop.pll_hz", "number", "The same in Hz."),
        ("lanes[].loop.clamp_q213", "number", "The loop's clamp."),
        ("lanes[].loop.hot", "bool", "At half the clamp or more: running on noise."),
    ],
    "/api/v1/config": [
        ("format", "string", "`scanner-config`."),
        ("version", "number", "The document's version."),
        ("build", "string", "The build that exported it."),
        ("exported_unix_ms", "number", "When."),
        ("radio", "object", "The radio settings."),
        ("@radio", "radio_config"),
        ("systems", "object", "The systems file."),
        ("systems.version", "number", "Its format's version."),
        ("systems.systems", "array", "Every system."),
        ("@systems.systems[]", "system"),
        ("live_site", "string or null", "The live site."),
    ],
    "/api/v1/radio": [
        ("presets", "array of strings", "Every DDC preset the gateware has, narrowest first."),
        ("presets[]", "string", "One preset."),
        ("config", "object", "The radio settings."),
        ("@config", "radio_config"),
        ("state", "object", "What the radio keeps between runs."),
        ("state.version", "number", "The file's version."),
        ("state.live_site", "string or null", "The site made live at start."),
        ("state.crystal", "object or null", "The stored crystal correction."),
        ("state.crystal.ppm", "number", "The correction."),
        ("state.crystal.measured_at_lo_hz", "number", "The LO it was measured at."),
        ("state.crystal.lo_shift_hz", "number", "The shift it gave there."),
        ("state.crystal.control_freq_hz", "number or null", "The control channel it was measured on."),
        ("state.crystal.method", "string", "How: `calibration` or `tracker`."),
        ("state.crystal.at_unix_ms", "number", "When."),
        ("hardware", "object", "What the scanner found at start."),
        ("hardware.core_version", "string or null", "The gateware's version."),
        ("hardware.lanes", "number", "Traffic lanes running."),
        ("tuning", "object", "The tuning."),
        ("@tuning", "tuning"),
        ("readback", "object", "Values read back from the hardware."),
        ("readback.lo_hz", "number or null", "The AD9361's LO."),
        ("readback.gain_db", "number or null", "The AD9361's gain."),
        ("readback.rssi_db", "number or null", "The AD9361's RSSI (dB below full scale)."),
        ("readback.gain_mode", "string or null", "The AD9361's gain mode."),
        ("readback.control_nco_hz", "number or null", "The control chain's NCO offset from the LO."),
        ("readback.control_lsm", "object or null", "The control chain's LSM settings."),
        ("@readback.control_lsm", "lsm_control"),
        ("readback.control_nid", "array of 2 numbers or null", "NAC and DUID of the latest frame the control LSM decoded."),
        ("readback.control_status", "object or null", "The control LSM's status register."),
        ("readback.control_status.bch_busy", "bool", "The BCH decoder is busy."),
        ("readback.control_status.in_nid_window", "bool", "Inside a NID."),
        ("readback.control_status.nid_event", "bool", "A NID was decoded."),
        ("readback.control_status.nid_valid", "bool", "It passed BCH."),
        ("readback.control_status.n_errors", "number", "Bit errors BCH corrected."),
        ("readback.control_status.sync_distance", "number", "The sync correlator's distance."),
        ("readback.control_status.dibit_overflow", "bool", "The dibit FIFO overflowed."),
        ("readback.lane_nco_hz", "array of 2 numbers or null", "Each lane's NCO offset from the LO."),
        ("readback.lane_lsm", "array of 2 objects or null", "Each lane's LSM settings."),
        ("@readback.lane_lsm[]", "lsm_control"),
    ],
    "/api/v1/radio/crystal": [
        ("ppm", "number", "The correction applied."),
        ("lo_shift_hz", "number", "The shift it gives at the current LO."),
        ("tracking", "bool", "Tracking is on."),
        ("anchor_hz", "number", "How far tracking may move from this run's calibration, Hz (0: no limit)."),
        ("anchor_ppm", "number or null", "The calibration tracking is anchored to."),
        ("source", "string or null", "What tracking measures now: `p25_loop`, `dmr_equaliser` or `spectrum`."),
        ("estimate_ppm", "number or null", "Tracking's current estimate (applied each minute within the anchor)."),
        ("samples", "number", "Readings in the estimate."),
        ("last_decision", "string or null", "Tracking's last move."),
        ("calibrating", "bool", "A calibration runs now."),
        ("calibration", "object or null", "This run's calibration."),
        ("@calibration", "crystal_cal"),
    ],
    "/api/v1/recordings": [
        ("total", "number", "Recordings of the listed site (all, without `site`)."),
        ("items", "array", "Recordings newest first (`limit`, `site`)."),
        ("@items[]", "recording"),
        ("storage", "object", "The stores."),
        ("storage.enabled", "bool", "Recording is on."),
        ("storage.store", "string", "Where new recordings go: `sd` or `ram`."),
        ("storage.ram", "object", "RAM's recordings."),
        ("storage.ram.count", "number", "Recordings."),
        ("storage.ram.bytes", "number", "Their size."),
        ("storage.ram_max_count", "number", "The most RAM keeps."),
        ("storage.sd", "object", "The card's recordings."),
        ("storage.sd.count", "number", "Recordings."),
        ("storage.sd.bytes", "number", "Their size."),
        ("storage.sd_max_count", "number", "The most the card keeps."),
        ("storage.sd_max_bytes", "number", "The space they may use."),
        ("storage.sd_status", "object", "The card."),
        ("storage.sd_status.state", "string", "`unknown`, `ok`, `absent`, `read_only`, `full` or `error`."),
        ("storage.sd_status.detail", "string or null", "More on the state."),
        ("storage.sd_status.dir", "string", "The recordings' directory."),
        ("storage.sd_status.total_bytes", "number or null", "The card's size."),
        ("storage.sd_status.free_bytes", "number or null", "Free space."),
        ("storage.sd_status.writes_ok", "number", "Recordings written."),
        ("storage.sd_status.writes_failed", "number", "Writes that failed."),
        ("storage.sd_status.fallbacks_to_ram", "number", "Recordings kept in RAM because the card could not take them."),
        ("storage.sd_status.deletes", "number", "Files deleted (retention, or by hand)."),
        ("storage.sd_status.last_write_ms", "number or null", "The last write's duration."),
        ("storage.sd_status.max_write_ms", "number", "The longest write."),
        ("storage.sd_status.last_error", "string or null", "The last error."),
        ("storage.sd_status.last_probe_unix_ms", "number or null", "When the card was last checked."),
        ("storage.sd_status.indexed_at_boot", "number", "Recordings found on the card at start."),
        ("storage.sd_status.index_note", "string", "What the start found."),
        ("storage.sd_status.queue_jobs", "number", "Writes and deletes waiting."),
        ("storage.sd_status.queue_bytes", "number", "Bytes waiting."),
        ("storage.sd_status.writing_for_ms", "number or null", "How long the current write has taken."),
        ("storage.sd_status.writer_running", "bool", "The card's writer runs."),
        ("storage.recording_now", "number", "Calls being recorded now."),
        ("storage.counters", "object", "Since start."),
        ("storage.counters.saved", "number", "Recordings saved."),
        ("storage.counters.no_audio", "number", "Followed calls with no audio (not saved)."),
        ("storage.counters.off", "number", "Calls not recorded because recording was off."),
        ("storage.counters.failed", "number", "Recordings that could not be saved."),
        ("storage.counters.unmatched_chunks", "number", "Audio no call claimed."),
        ("storage.counters.missed_chunks", "number", "Audio lost before the recorder got it."),
    ],
    "/api/v1/systems": [("[]", "object", "One system."), ("@[]", "system")],
    "/api/v1/systems/{id}": [("@", "system")],
    "/api/v1/sites": [
        ("[]", "object", "One site: its configuration and the fields below."),
        ("[].system", "string", "Its system's id."),
        ("[].system_label", "string", "Its system's name."),
        ("[].protocol", "string", "`p25` or `dmr_tier3`."),
        ("[].live", "bool", "It is the live site."),
        ("@[]", "site"),
    ],
    "/api/v1/sites/{id}/learned": [
        ("version", "number", "The file's version."),
        ("iden_bands", "array", "P25: the band plan the site announces (IDEN_UP)."),
        ("iden_bands[]", "object", "One band."),
        ("iden_bands[].identifier", "number", "The band's identifier (the first part of a channel's `iden-number`)."),
        ("iden_bands[].base_frequency_hz", "number", "Channel 0's frequency."),
        ("iden_bands[].channel_spacing_hz", "number", "Channel spacing."),
        ("iden_bands[].bandwidth_hz", "number", "Channel bandwidth."),
        ("iden_bands[].transmit_offset_hz", "number", "Uplink offset."),
        ("iden_bands[].slots", "number", "TDMA slots per channel (1: FDMA)."),
        ("grants", "map", "Grants per traffic channel (key: Hz), what the window planner weighs."),
        ("grants{key}", "number", "Grants on that channel."),
        ("encrypted_talkgroups", "array of numbers", "Talkgroups seen encrypted."),
        ("last_recentre_unix_ms", "number", "The window's last move."),
        ("neighbours", "array", "Neighbour sites announced."),
        ("neighbours[]", "object", "One neighbour."),
        ("neighbours[].system", "number", "Its system."),
        ("neighbours[].rfss", "number", "Its RFSS."),
        ("neighbours[].site", "number", "Its site."),
        ("neighbours[].control_hz", "number or null", "Its control channel, once the band plan names it."),
        ("neighbours[].last_heard_unix_ms", "number", "Last announced."),
        ("secondary_control_hz", "array of numbers", "The site's other control channels."),
        ("data_channel_hz", "number or null", "The data channel it announces."),
    ],
    "/api/v1/sites/{id}/plan": [
        ("site", "string", "The live site."),
        ("auto", "bool", "The planner chooses the window."),
        ("min_preset", "string or null", "The narrowest preset allowed."),
        ("preset", "string or null", "The window's preset now."),
        ("sample_rate_hz", "number", "Its width."),
        ("lo_hz", "number", "Its centre."),
        ("control_hz", "number", "The control channel."),
        ("channels", "array", "The site's channels."),
        ("channels[]", "object", "One channel."),
        ("channels[].freq_hz", "number", "The channel."),
        ("channels[].grants", "number", "Grants seen on it."),
        ("channels[].listed", "bool", "In the site's configuration."),
        ("channels[].weight", "number", "Its weight in the plan."),
        ("channels[].covered", "bool", "Inside the window now."),
        ("covered_weight", "number", "The weight inside the window."),
        ("total_weight", "number", "The weight of all channels."),
        ("best", "object or null", "The planner's choice now."),
        ("@best", "window_plan"),
        ("better", "bool", "The choice covers more than the window does."),
        ("last_recentre_unix_ms", "number", "The window's last move."),
    ],
    "/api/v1/scan/options": [
        ("bands", "array", "The bands a scan offers by name; all are scanned when a scan names none."),
        ("bands[]", "object", "One band."),
        ("bands[].name", "string", "`700 MHz`, `800 MHz`, `900 MHz`, `UHF` or `VHF`."),
        ("bands[].low_hz", "number", "Its bottom."),
        ("bands[].high_hz", "number", "Its top."),
        ("defaults", "object", "The settings a scan takes when its request leaves them out."),
        ("defaults.bands", "array", "Empty: every band."),
        ("defaults.frames", "number", "Spectrometer frames read at each window."),
        ("defaults.probe_ms", "number", "Time listening to a carrier before deciding it carries no control channel."),
        ("defaults.identity_ms", "number", "Longest wait for a site's identity."),
        ("defaults.max_candidates", "number", "Carriers probed at most, the strongest first."),
        ("window_hz", "number", "How much the radio reads at a time (the sweep's sample rate)."),
        ("usable_hz", "number", "The part of a window clear of the decimator's edges."),
        ("step_hz", "number", "How far apart the windows are (they overlap by 10 %)."),
    ],
    "/api/v1/scan": [
        ("id", "number", "The scan's number."),
        ("state", "string", "`idle`, `sweeping`, `probing`, `restoring`, `done`, `cancelled` or `error`."),
        ("started_unix_ms", "number", "Its start."),
        ("finished_unix_ms", "number", "Its end (0 while running)."),
        ("bands", "array", "The bands swept."),
        ("bands[]", "array of 2 numbers", "From and to, Hz."),
        ("band", "array of 2 numbers or null", "The band of the window read now (from and to, Hz); null while the control channels found sites announced are checked, and when no scan runs."),
        ("lo_hz", "number or null", "The centre of the window read now."),
        ("step", "number", "The sweep's step."),
        ("steps", "number", "Its steps."),
        ("probed", "number", "Carriers probed for a control channel."),
        ("to_probe", "number", "Carriers to probe."),
        ("probing_hz", "number or null", "The carrier being probed."),
        ("carriers", "number", "Carriers found."),
        ("sites", "array", "Control channels found."),
        ("sites[]", "object", "One control channel."),
        ("sites[].id", "string", "Its key (what `add` names)."),
        ("sites[].freq_hz", "number", "The channel."),
        ("sites[].level_db", "number", "Its level, dB."),
        ("sites[].protocol", "string", "`p25` or `dmr_tier3`."),
        ("sites[].modulation", "string or null", "P25: `lsm` or `c4fm`, whichever decoded better."),
        ("sites[].msgs_per_s", "number", "Messages per second while probed."),
        ("sites[].ok_pct", "number", "Share that passed, %."),
        ("sites[].identity", "object", "Its identity; `protocol` says which fields follow."),
        ("@sites[].identity", "heard_identity"),
        ("sites[].bands", "array", "P25: its band plan."),
        ("sites[].bands[]", "object", "One band (as `iden_bands` in `/learned`)."),
        ("sites[].bands[].identifier", "number", "The band's identifier."),
        ("sites[].bands[].base_frequency_hz", "number", "Channel 0's frequency."),
        ("sites[].bands[].channel_spacing_hz", "number", "Channel spacing."),
        ("sites[].bands[].bandwidth_hz", "number", "Channel bandwidth."),
        ("sites[].bands[].transmit_offset_hz", "number", "Uplink offset."),
        ("sites[].bands[].slots", "number", "TDMA slots per channel."),
        ("sites[].neighbours", "array", "Neighbours it announces."),
        ("sites[].neighbours[]", "object", "One neighbour."),
        ("sites[].neighbours[].system", "number", "Its system."),
        ("sites[].neighbours[].rfss", "number", "Its RFSS."),
        ("sites[].neighbours[].site", "number", "Its site."),
        ("sites[].neighbours[].freq_hz", "number or null", "Its control channel."),
        ("sites[].secondary_hz", "array of numbers", "P25: the control channels it announces."),
        ("sites[].timeslot", "number or null", "DMR: the control timeslot."),
        ("sites[].existing_site", "string or null", "The configured site it is."),
        ("sites[].via_neighbour", "bool", "Found as a neighbour's control channel, not in the spectrum."),
        ("traffic", "array", "Carriers with a protocol's frames but no control messages (traffic channels)."),
        ("@traffic[]", "carrier"),
        ("other", "array", "Continuous carriers no protocol recognised."),
        ("@other[]", "carrier"),
        ("error", "string or null", "What went wrong."),
    ],
    "/api/v1/systems/{id}/aliases": [
        ("aliases", "array", "The system's aliases."),
        ("@aliases[]", "alias"),
        ("listening", "object", "Talkgroups with no priority, and pre-emption."),
        ("@listening", "listening"),
    ],
    "/api/system": [
        ("build", "string", "The build tag."),
        ("uptime_s", "number", "Since start, s."),
    ],
    "/api/ui/state": [
        ("v", "number", "The shape's version (1)."),
        ("build", "string", "The build tag."),
        ("now_unix_ms", "number", "The board's clock."),
        ("clock_valid", "bool", "The clock has been set."),
    ],
    "/api/imbe_dump": [
        ("count", "number", "Frames returned."),
        ("frames", "array", "The newest raw IMBE frames (at most 128), oldest first."),
        ("frames[]", "object", "One frame."),
        ("frames[].talkgroup", "number", "The talkgroup."),
        ("frames[].encrypted", "bool", "Encrypted."),
        ("frames[].hex", "string", "The 18-byte frame, hex."),
    ],
    "/api/ui/calls": [
        ("now_unix_ms", "number", "The board's clock."),
        ("items", "array", "Open and recent calls, newest first (`limit`)."),
        ("items[]", "object", "One call."),
        ("items[].call_id", "number", "The call."),
        ("items[].tg", "number", "The talkgroup."),
        ("items[].source", "number or null", "The calling radio."),
        ("items[].sources", "array of numbers", "Every radio heard."),
        ("items[].freq_hz", "number or null", "The channel."),
        ("items[].started_unix_ms", "number", "The grant."),
        ("items[].ended_unix_ms", "number or null", "The close."),
        ("items[].open_ms", "number", "From the grant to the close (to now while open)."),
        ("items[].first_voice_ms", "number or null", "From the grant to the first voice."),
        ("items[].imbe", "number", "Voice frames."),
        ("items[].voice_ms", "number", "Voice, ms."),
        ("items[].encrypted", "bool", "Encrypted."),
        ("items[].not_followed", "string or null", "Why not followed."),
        ("items[].close_reason", "string or null", "Why it closed."),
    ],
    "/api/ui/settings": [
        ("settings", "object", "The settings the bench reads."),
        ("settings.clock", "object", "The board clock."),
        ("settings.clock.source", "string", "`site`, `ntp` or `manual`."),
    ],
}

NOT_JSON: dict[str, str] = {
    "/ws/live": (
        "A WebSocket of text frames, each a JSON object with `type`; the payload is under the key named:\n\n"
        "| `type` | Key | When |\n|--------|-----|------|\n"
        "| `snapshot` | `status`, `calls` (`open`, `recent`), `traffic`, `scan` | On connect, and after `lag`. |\n"
        "| `status` | `status` (as `GET /api/v1/status`) | Each second, and at once when the live site changes. |\n"
        "| `traffic` | `traffic`: `channels[]` (each traffic channel: `lane`, `tuned_hz`, `following_tg`, `on_data_channel`, `voice_frames`, `last_voice_ms_ago`, `call`) and `open[]` (every call on the air) | When a traffic channel changes. |\n"
        "| `call_opened`, `call_closed` | `call` (as `GET /api/v1/calls/{id}`) | As a call opens or closes. |\n"
        "| `recording` | `recording` (as an item of `GET /api/v1/recordings`) | As a recording is saved. |\n"
        "| `scan` | `scan` (as `GET /api/v1/scan`) | While a scan runs, as its progress or found sites change. |\n"
        "| `changed` | `what`: `radio`, `systems`, `hold` or `recordings` | After a write changed that part: read it again. |\n"
        "| `lag` | | The listener fell behind; a snapshot follows. |"
    ),
    "/ws/events": (
        "A WebSocket of text frames, each a JSON object with `type`:\n\n"
        "| `type` | Fields | When |\n|--------|--------|------|\n"
        "| `call_opened` | `call`, `tg`, `followed` | A call opened (followed: a lane took it). |\n"
        "| `call_closed` | `call`, `tg` | A call closed. |\n"
        "| `recording_saved` | `call` | Its recording was saved. |\n"
        "| `lag` | | The listener fell behind and missed notices: read the state again. |"
    ),
    "/ws/audio": (
        "A WebSocket. Binary frames are 20 ms of 8 kHz mono 16-bit little-endian audio (160 samples). "
        "With `?v=2` every lane is sent and each frame starts with 4 bytes `[lane, 0, 0, 0]` (lane 0 "
        "or 1); without it, lane 1 only and no header. Text frames:\n\n"
        "| `type` | Fields | When |\n|--------|--------|------|\n"
        "| `meta` | `lane` (0 or 1), `tg`, `src` (0: unknown), `call_id`, `speaker` (`both`, `left`, `right`, `off`) | Before a lane's first frame of a new call or talker. |\n"
        "| `lag` | `skipped` | The listener fell behind; frames were skipped. |"
    ),
    "/api/v1/iq/control.wav": (
        "A WAV file (`audio/wav`, an attachment named like `cc_454368750_20261002_002754_60s.wav`): "
        "the control channel's IQ at 50 kSPS, 16-bit stereo, I left and Q right, as the decoder gets "
        "it. 409 when no site is live or its decoder reads only the gateware's dibits."
    ),
    "/api/v1/recordings/{id}": (
        "The recording's WAV (`audio/wav`): 8 kHz 16-bit mono. Byte ranges are honoured (206 with "
        "`Content-Range`)."
    ),
}
